services:
  - type: web
    name: visaai-backend
    repo: https://github.com/amine8111/GeminiVisaAi.git
    branch: main
    rootDir: backend
    runtime: python311
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: DATABASE_URL
        value: postgresql://visaai:XTo3cmnd3tclrEMm6naYKYHWB7FrQ3Pr@dpg-d6tr89paae7s73e49660-a/visaai
      - key: SECRET_KEY
        value: gemini-visa-ai-secret-key-2024
      - key: FRONTEND_URL
        value: https://visa-ai-one.vercel.app
      - key: TELEGRAM_BOT_TOKEN
        value: 8521780664:AAF-mbh2Lz9e3qY2qABMQE3V0KpDv0go9KY